name: update-build-config

on:
  schedule:
    # 0:30
    - cron: "30 0 * * *"

jobs:
  Update-Build-Configuration:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
        # Use personal access token for cloning (and later pushing) code
        with:
          token: ${{ secrets.CI_TOKEN }}

      - name: Prepare branch nightly/update-build-configuration
        run: |
          set -exo pipefail
          git fetch --quiet
          git checkout -B nightly/update-build-configuration
          git reset --hard ${GITHUB_REF#refs/heads/}

      - name: Use Node.js 12.19.0
        uses: actions/setup-node@v1
        with:
          node-version: 12.19.0
          registry-url: https://npm.pkg.github.com/
          scope: "@sealsystems"

      - name: Cache Node.js modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-12.19.0-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        run: npm i
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Install Yeoman
        run: npm install --no-save --force yo @sealsystems/generator-seal-node
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Update build config
        run: npx yo @sealsystems/seal-node:oss-module --force
        env:
          # Use personal access token, must be set for *each step*
          NODE_AUTH_TOKEN: ${{ secrets.CI_TOKEN }}

      - name: Check for modifications other than package-lock.json
        run: |
          git add .
          # Remove package-lock.json from index
          git reset -- package-lock.json
          if git diff --cached --exit-code; then
            echo "No relevant changes made. Skip creating pull request."
          else
            echo "CREATE_PR=1" >> $GITHUB_ENV
          fi

      - name: Commit changes into branch nightly/update-build-configuration
        if: ${{ env.CREATE_PR == '1' }}
        run: |
          # Commit and push changes
          git add .
          git config --local user.email "com.git@sealsystems.de"
          git config --local user.name "${GITHUB_ACTOR}"
          git commit -m "Update build configuration"
          git push --force origin nightly/update-build-configuration

      - name: Create pull request
        if: ${{ env.CREATE_PR == '1' }}
        run: |
          set -exo pipefail

          # Only create a new PR if there is not already another one
          # Use variable for debugging purposes
          LIST="$(gh pr list)"
          if echo "${LIST}" | grep -q "nightly/update-build-configuration"; then
            echo "PR already exists. Skip creating a new one."
            exit 0
          fi

          if [ -n "com-infrastructure" ]; then
            reviewerOption="--reviewer com-infrastructure"
          fi

          gh pr create \
          --base "master" \
          --title "Update build configuration" \
          --body "The build configuration of this project is outdated and may no longer work.
          This pull request will be merged automatically if there are no conflicts." \
          ${reviewerOption}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
